### ISSUE TITLE
just out of curiosity

### ISSUE THREAD

**Issue by ttdonovan** [nfpiche/crystal_monads#1]
Just curious if before you created this library did you search for any other monad libs. I started this awhile ago but got distracted with other work. Is there something your lib does better or that I had done wrong? Thanks for listening.

https://github.com/dry-cr/dry-monads

**Comment by nfpiche** [comment]
This is just for my own practice learning crystal, not expecting it to be of any use :)

**Comment by nfpiche** [comment]
Just grabbed your repo, there is a failing test case from the dry-rb Either module if you're interested in a PR,

```
      it "passes extra arguments to proc" do
        proc = -> (value : Int32, c : Symbol) do
          expect(value).to eq(5)
          expect(c).to eq(:foo)
          true
        end

        expect(subject.bind(proc, :foo)).to be_true
      end
```
